### PR TITLE
 PVE TONK BUFFS

### PR DESCRIPTION
**Pull request by Kirshbia**
# About the pull request

# Changelog
:cl:
balance: Adjusted the tank for PVE.
Adjusted all hardpoint HP and damage multipliers.
Increased fire-rates for some weapons
Increased damage on some weapons
/:cl:

### CODE REVIEW

**Review by Kirshbia — COMMENTED** [review]
Adjustment to the AUTOCANON

**Review by Kirshbia — COMMENTED** [review]
Adjustments made to  testing. Increased ACE damage. Decreased minigun fire-rate and brought all hardpoint parts HP in alignment with each other and reduced the multiplier.

**Review by Kirshbia — COMMENTED** [review]
Adjustments made to ACE, LTB, minigun.

All damage multipliers on hardpoints reduced. 
All HP on hardpoint parts brought in line with each other.

**Review by Kirshbia — COMMENTED** [review]
Additional increases to Autocanon, LTB, and TOW

**Review by Kirshbia — COMMENTED** [review]
Fixing a small whoopsie

**Comment by Kirshbia** [comment]
Also from last commit. 

Increased the speed of the turret turning from 15 seconds to 5.

**Comment by Kirshbia** [comment]
yeah, at this point. Tank is in a good place. There some things I MIGHT wanna do with it later time permitting but now it's actually kinda useful if GM's wish to use it. It's good to merge.

**Review by morrowwolf — APPROVED** [review]

**Pull request merged**
