### PR TITLE
Runner should no longer get stuck on some structures when capture dragging

### PR DESCRIPTION
**Pull request by BeagleGaming1**
# About the pull request

Potentially fixes an issue with runner capture dragging pathfinding

# Explain why it's good for the game

Bug bad

# Changelog

:cl:
code: Runners should no longer have pathfinding issues when attempting to capture drag a human
/:cl:

### CODE REVIEW

**Comment by fira** [comment]
I don't think initial() on pass_flags is going to work the way you want, it'd just be null

**Comment by morrowwolf** [comment]
Yeah we talked about on discord, forgot to mention it here

**Comment by morrowwolf** [comment]
image
image

Go look at the datum you're manipulating. That var itself isn't bitflags.

**Comment by fira** [comment]
You shouldn't manipulate the pass_flags container EVER, it's cached and shared across all instances of the type

That's why you'd traditionally use temp_pass_flags variables

**Comment by morrowwolf** [comment]
https://github.com/PvE-CMSS13/PvE-CMSS13/commit/d55cfcb7f33525c48aea0e7a40a8ede23032975e

**Pull request closed without merging**
