### PR TITLE
M44 sprite and sound changes

### PR DESCRIPTION
**Pull request by DexterDude**
Changes the sprites and sounds of the M44 revolver to make it sound and look a little more beefy overall. Before it sounded a little flat and the audio for most of its sounds was very...meh and flat in my opinion. The UPP revolver sounds are far better, though I'd appreciate input.

The sprites changed simply make it a little more beefy.

Credit to dongwaiver on discord for the sprites, i just added them

prchange

https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/8fbe0b17-7b13-4e08-a884-d9f4000787bf

### CODE REVIEW

**Comment by AndroBetel** [comment]
imagine NOT crediting the sprote author

**Comment by DexterDude** [comment]
> imagine NOT crediting the sprote author

No clue what youre talking about mr jeremy loyd!

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Eh, I like the other sound better.

Also make sure to credit the sprite author in the PR description please.

**Comment by DexterDude** [comment]
> Eh, I like the other sound better.
> 
> Also make sure to credit the sprite author in the PR description please.

They are credited. What sound, firing?

**Comment by morrowwolf** [comment]
Yeah

**Comment by Ollanius** [comment]
If Amory's pull request _(that changes the wooden palette for the Shotgun and Revolver)_ ends up being merged, let me know and I'll send a color-corrected version of this .dmi.

**Review by morrowwolf — APPROVED** [review]

**Pull request merged**
