### PR TITLE
emote and talking length

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
# About the pull request

increases emote/say length. it was capped rly low for some reason. 256 is really not a whole lot of characters. this is already 131.

# Explain why it's good for the game

RP...good

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: emote length
/:cl:

### CODE REVIEW

**Comment by DexterDude** [comment]
rp bad

**Comment by KoishiVibe** [comment]
> rp bad

failrp
admemes ban he

**Review by FslashN — COMMENTED** [review]
There are good reasons for having a message limit, and I don't know that having huge-large emote length is a good thing, either. Text already takes a while to render when you're speaking large sections of it.

**Comment by Skycave1** [comment]
The default SS13 message limit is 2056, and CM back in it's hayday ran fine with the default limits in play. I've noticed whenever you play on a server with a character limit higher than the default is when things start to chug, and that's generally on servers hosting more than 20 people at a time.  Plus we have green shift and having your message cut off because of a limit as comically low as 256 is just bad for practice and stifles certain avenues of RP. Maybe I left CM and changed, but some great stories came out of CM back in 2014/15 because of said character limit. Albeit rare, it was always fun to see

And I wanna spite Aero and Columbo post (4k character me;) just to make them angy.

**Comment by bearrrrrrrr** [comment]
> There are good reasons for having a message limit, and I don't know that having huge-large emote length is a good thing, either. Text already takes a while to render when you're speaking large sections of it.

256 characters for an emote length is pretty low. 2048 was a random, arbitrary number I picked. I can put it at par w/ say, if that's better for you. I don't really mind- I'm probably just an outlier, but I have actually genuinely had my emotes cut off.

^ This is above the emote limit, by the way

**Comment by bearrrrrrrr** [comment]
To add on; in most normal rounds, it doesn't matter. In greenshifts, it hurts a lil, and I think (iirc) it has happened to people other than just me.

**Comment by Skycave1** [comment]
> To add on; in most normal rounds, it doesn't matter. In greenshifts, it hurts a lil, and I think (iirc) it has happened to people other than just me.

I think a limit of 2k is good, but that is just my dumb ass, and it is bellow the default cap as it is.  Dare we spaghetti code a 4k character limit?

**Review by morrowwolf — APPROVED** [review]

**Pull request merged**
