### PR TITLE
Movie Accurate M10s

### PR DESCRIPTION
**Pull request by Max-023**
Adds new M10 sprites for Riflemen, SGTs, and Corpsmen that is more accurate to the movies. Old sprites are still there, now just no longer used.

Also adds integrated headset component to allow for attaching headsets to headgear. Shown: https://www.youtube.com/watch?v=V34R6HBdFb0

### CODE REVIEW

**Comment by FslashN** [comment]
Can you post a screenshot? I don't think I've seen what these look like.

**Comment by Max-023** [comment]
image
This is what the helmet looks like, shown with the rest of the gear. Additional strapping is layered over the helmet, as well as the camera and radio now being part of the sprite in visual form. I've also adjusted corpsman and platoon sergeant helmets to have the same additions, though the corpsman helmet lacks the additional strapping.

It is notable that not all helmet accessories have yet been adjusted as to not look out of place with the altered helmet, but should this work be to your liking I can certainly fix that.

**Comment by FslashN** [comment]
I like the change. Looks neato. If you would like to adjust accessories so they look right with the cam, go for it. It's on auto-merge, when you fix the icon conflict.

**Comment by Max-023** [comment]
Aight, will do!

**Comment by grifp71** [comment]
looks like this is still reverting amory's sprite changes to other headgear like the boonie according to iconbot

**Comment by Max-023** [comment]
I wasn't aware he made changes to the softcap headgear so when I get back home I'll match sure to patch those in.

**Comment by Max-023** [comment]
Alright, that should fix this PR.

**Comment by AmoryBlaine** [comment]
> Alright, that should fix this PR.

You're still overriding the new PO helmet, and desert cap and its flipped state with the old shading. I will also say, I'm not sure why you're integrating a mic into the helmet when we have a earpiece system. Adding a mic piece communicates something that doesn't exist. The helmets do have camera functionality, they don't have earpiece functionality.

**Comment by Max-023** [comment]
Added the PO helmet and new desert patrol cap. The changes are there to provide an aesthetic change to match that of the movie this project is based on. While yes, the helmet doesn't have a built in radio function code wise, that could be changed in the future.

**Comment by FslashN** [comment]
Hmmm... Okay, we will TM this and see what does that. I'm fine with the helmet ear pieces, and in fact may be something we will do in the future. But if it's out of place, we probably want to remove that before merging it in proper.

**Comment by ValoTheValo** [comment]
not the biggest fan of this change. the headset and mic i think looks great but the tactical light ends up causing problems. 

the helmet looks fine on its own but with the change it heavily limits customization of your helmet. as now all band items are forced to be on one side, and now pretty much everything overlaps. i also had some issues during test where some accessories just straight up didnt show up like the shotgun shells that were just invisible and a pack of WY gold cigs that were clipping with the light.

that and the tactical light sprite just looks abit off in general as it doesn't really look like its attached to the side of the helmet

**Comment by Max-023** [comment]
I manually adjusted all the sprites to not clip through the headset, so I'll try to see what is going on to make that occur.

I could try to bake in the helmet cam a bit more, as well, to make it seem better attached.

**Review by morrowwolf — DISMISSED** [review]
Anything deprecated should be removed. It'll be stored by github/git if we ever need it again.

I think the camera is cool but I am worried about accessories as others have stated. Honestly, I think the camera should be an accessory itself and that'd likely make people more likely to engage with the change positively.

**Comment by Max-023** [comment]
I could look into adding it as an accessory. I would need to coordinate with someone more adept with coding in order to separate the cam function to an accessory.

**Comment by DexterDude** [comment]
I cant say i'm a fan of this PR. Although I like the idea of cameras being visual, and perhaps they should be on the helmet, as others have stated it may interfere with customization. What mostly concerns me is the implementation of the headset to the helmet. I think it's important to retain visual clarity, having a helmet get a headset but not automatically give comms access seems odd. An option would be to just make the headset appear on the character visually and have it so that when the helmet is on it looks like it is now? That way we retain visual clarity and get a nice little sprite for headsets and such. But this may also interfere with customization and look odd with certain headwear, so I cant really say i'm fond of it overall?

**Comment by Max-023** [comment]
While I would agree, that the optimal scenario is that the helmet provides radio communication as to bring it in line with how its depicted in Aliens media, I do contest the idea that this is a change from form. The caps worn by officers have headsets drawn on their sprites, yet they do not offer communication themselves. The sprite change like this should be treated no differently just because it doesn't have a historic precedent.

I am more than willing to look into having radio headsets be integrated into helmets/headwear rather than be a separate item, as well as look into separating the helmet cameras out to be a real attachment with a visual attached. However, I'd rather not let this or other works fall to double standards that exist from convenience.

**Comment by AmoryBlaine** [comment]
> While I would agree, that the optimal scenario is that the helmet provides radio communication as to bring it in line with how its depicted in Aliens media, I do contest the idea that this is a change from form. The caps worn by officers have headsets drawn on their sprites, yet they do not offer communication themselves. The sprite change like this should be treated no differently just because it doesn't have a historic precedent.
> 
> I am more than willing to look into having radio headsets be integrated into helmets/headwear rather than be a separate item, as well as look into separating the helmet cameras out to be a real attachment with a visual attached. However, I'd rather not let this or other works fall to double standards that exist from convenience.

Those hats are old, I was the one most recently updated them but given I'm pursuing visible earpieces in the form of bowman headswta for marines, I didn't bother updating them when I did my most recent marine update. They'll ideally be chucked.

**Comment by morrowwolf** [comment]
Cooking

**Review by harryob — APPROVED** [review]
still a todo, i know. just for the code currently

**Comment by AmoryBlaine** [comment]
Played three rounds with it. Not really a fan. Visible camera is good, but I don't like how the headset bit is integrated. It's palette is very bland, and it does look like a helmet strap. Obviously I'm biased because I have my own sprites but I also just don't think it's that great to have it integrated with the helmet when you can just have visible headsets beneath to achieve the same outcome with much more versatility.

**Comment by XSlayer300** [comment]
I'd prefer if the headsets are around as surplus uniform vendors if anyone doesn't want to wear a helmet or those who never have a helmet in the first place.

**Comment by morrowwolf** [comment]
Gotta figure out how I want to handle some of the icons with multiple suffixes. So SoonTM.

**Comment by AndroBetel** [comment]
stale for more than a month, author seems to be inactive

**Pull request closed without merging**
