### PR TITLE
[WIP] derelict cargo ship wip

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
# About the pull request

starting to map another map. derelict cargo ship. heavy wip rn

# Explain why it's good for the game

new map good, mayhaps...

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

image

this is literally all so far lol

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by morrowwolf** [comment]
Hit "ready for review" at the bottom when you're ready

**Comment by bearrrrrrrr** [comment]
gigantic diff bc i moved the entire thing to center it again

**Comment by bearrrrrrrr** [comment]
augh i really don't know what to do with this for rn

gonna sit on it and come back to in a bit

**Comment by bearrrrrrrr** [comment]
no idea what to do w/ this one and i think i wanna redo this map entirely in the future. sorry!

**Pull request closed without merging**
