### PR TITLE
SMARTGUN BUFF

### PR DESCRIPTION
**Pull request by Kirshbia**
# About the pull request

Sadly, I may or may not of deleted my initial very fun project making the SG take all ammo types when I did a fresh windows install. 

HOWEVER,  I think in essence this should capture what I was going for and lay the groundwork for a future project with the CO smartgun for PVE. 

It carries a slight damage increase for SG's in AP mode as well as grants their regular rounds HOLO targeting effects which I think will help affirm them in the fire support category and let them feel cool when firing off those guns.

# Explain why it's good for the game

It's a small damage buff increase to SG's as well as adding a feature that will help solidify team play. When monkey brain see's yellow aura showing hit with holo I am hoping all neurons fire off and everyone moves to focus fire. The damage increase isn't too noticeable and I think it'll make the SG feel better to use.

# Changelog
:cl:
balance: Changed the SG's base auto type to HOLO rounds. Increased damage on AP rounds. 
/:cl:

### CODE REVIEW

**Comment by Kirshbia** [comment]
Small increase to damage as i believe the default SG datam is where the APC/M56 tank take their damage from.

**Review by morrowwolf — CHANGES_REQUESTED** [review]
Let me think about this one, default holo is pretty strong.

Also, you should really learn how to use branches as working off your master branch is generally a bad idea and creates the vomit of commits you see above there.

**Comment by Kirshbia** [comment]
> Let me think about this one, default holo is pretty strong.
> 
> Also, you should really learn how to use branches as working off your master branch is generally a bad idea and creates the vomit of commits you see above there.

Oh, for sure. On stand alone testing it wasn't too noticeable of a difference. I totally want to actually see what it would result in practical gameplay.

**Review by AndroBetel — COMMENTED** [review]
don't really like holorounds, as they feel too "gamey" with blue aura and increased damage for friendlies

if anything, just buff smartguns damage if it feels too weak

**Comment by FslashN** [comment]
Holy commits, Batman! But yeah, what Andro stated. Getting rid of the toggle and upping the damage; the toggle doesn't make any logical or lore sense anyway.

**Comment by morrowwolf** [comment]
I just don't really like holo rounds sadly. The other PR buffing smartgunners is definitely cooking though so soonTM smartgunners will get some love.

**Pull request closed without merging**
