### PR TITLE
Movielike Spawning (Satchel on Spawn Removal)

### PR DESCRIPTION
**Pull request by Max-023**
Removes satchels from cryospawn loadouts, as personnel lockers have rendered them unnecessary. Additionally, adds the service cap to the PltCO's loadout to complete the service uniform set and adds the officer cap to the wardrobe.

### CODE REVIEW

**Comment by AmoryBlaine** [comment]
The service jackets are a part of the service uniform. The whole ensemble should be in there if you're gonna put the jackets in. You don't see guys walking around with BDUs, combat boots and their service uniform jackets.

**Comment by Max-023** [comment]
Fixed

**Comment by Max-023** [comment]
I'll remove it from the lockers for now then and come up with another way to include them.

**Comment by Max-023** [comment]
The boiler suit palette adjustment is more for the fact that I am trying to make sure this PR remains compatible with PR#173. Adjusting CM_hats.dmi would make it conflict with said PR. Once that PR is merged, the plan was to adjust the suits back and make the caps use the boiler suit palette, rather than the officer service uniform.

**Comment by morrowwolf** [comment]
Conflicts

**Review by morrowwolf — CHANGES_REQUESTED** [review]
If there's nothing in the function any longer you should remove the typepath/proc override.

**Comment by AndroBetel** [comment]
stale for more than a month, author seems to be inactive

**Pull request closed without merging**
